<?php
/**
 *  @category   Hatimeria
 *  @author     (office@hatimeria.com)
 *  @copyright  Copyright (c) 2020 Hatimeria Sp. z o.o. Sp. k. ( https://www.hatimeria.com/ )
 *  @license    (https://www.gnu.org/licenses/gpl-3.0.html)
 */

/** @var \Hatimeria\GtmPro\Block\DataLayer $block */
// @codingStandardsIgnoreFile
?>
<script>
    window.dataLayer = window.dataLayer || [];
    <?php foreach ($block->getDataLayerStaticData() as $event): ?>
    window.dataLayer.push(<?= json_encode($event) ?>);
    <?php endforeach; ?>
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "data-layer-data": {}
        }
    }
</script>