<?php
/** @var \Hatimeria\GtmPro\Block\Event\ProductClick $block */
// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
    {
        "*": {
            "product-click-event": {
                "productClasses": <?= json_encode($block->getProductClickClasses()) ?>,
                "productClickElementClass": "<?= $block->getProductClickElementClass() ?>"
            }
        }
    }
</script>