<?php
/**
 *  @category   Hatimeria
 *  @author      (office@hatimeria.com)
 *  @copyright  Copyright (c) 2020 Hatimeria Sp. z o.o. Sp. k. ( https://www.hatimeria.com/ )
 *  @license    (https://www.gnu.org/licenses/gpl-3.0.html)
 */

/** @var \Hatimeria\GtmPro\Block\Event\ProductClick $block */
// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
    {
        "*": {
            "product-click-event": {
                "productClasses": <?= json_encode($block->getProductClickClasses()) ?>,
                "productClickElementClass": "<?= $block->getProductClickElementClass() ?>"
            }
        }
    }
</script>