<?php
/** @var \Hatimeria\GtmEe\Block\Event\ProductImpression $block */
// @codingStandardsIgnoreFile
?>
<script type="text/javascript">
    require([
        "jquery"
    ], function ($) {
        const products = document.querySelectorAll('.<?= $block->getProductClass() ?>');
        window.dataLayer = window.dataLayer || [];
        observer = new IntersectionObserver(entries => {
            entries.forEach(entry => {
                if (entry.intersectionRatio > 0 && !$(entry.target).hasClass('intersection-viewed')) {
                    $(entry.target).addClass('intersection-viewed');
                    var impressionData = $(entry.target).find("*[data-impression]").data('impression');
                    addPositionToProductImpressionData(impressionData, entry);
                    window.dataLayer.push(impressionData);
                }
            });
        });

        products.forEach(image => {
            observer.observe(image);
        });
        
        function addPositionToProductImpressionData(impressionData, entry) {
            return impressionData['ecommerce']['impressions']['position'] = $(entry.target).index() + 1;
        }
    });
</script>