<?php
/**
 *  @category   Hatimeria
 *  @author      (office@hatimeria.com)
 *  @copyright  Copyright (c) 2020 Hatimeria Sp. z o.o. Sp. k. ( https://www.hatimeria.com/ )
 *  @license    (https://www.gnu.org/licenses/gpl-3.0.html)
 */

/** @var \Hatimeria\GtmPro\Block\Event\Promotion $block */
// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
    {
        "*": {
            "promotion-click-event": {},
            "promotion-impression-event": {}
        }
    }
</script>